<?php
return array (
  'ad_pos.container_breadcrumb_bottom_above' => 'Container breadcrumb (bottom): Above',
  'ad_pos.container_breadcrumb_bottom_below' => 'Container breadcrumb (bottom): Below',
  'ad_pos.container_breadcrumb_top_above' => 'Container breadcrumb (top): Above',
  'ad_pos.container_breadcrumb_top_below' => 'Container breadcrumb (top): Below',
  'ad_pos.container_content_above' => 'Container content: Above',
  'ad_pos.container_content_below' => 'Container content: Below',
  'ad_pos.container_header' => 'Container header',
  'ad_pos.container_sidebar_above' => 'Container sidebar: Above',
  'ad_pos.container_sidebar_below' => 'Container sidebar: Below',
  'ad_pos.container_sidenav_above' => 'Container sidenav: Above',
  'ad_pos.container_sidenav_below' => 'Container sidenav: Below',
  'ad_pos.forum_overview_bottom' => 'Forum overview: Bottom',
  'ad_pos.forum_overview_top' => 'Forum overview: Top',
  'ad_pos.forum_view_above_node_list' => 'Forum view: Above node list',
  'ad_pos.forum_view_above_thread_list' => 'Forum view: Above thread list',
  'ad_pos.forum_view_below_node_list' => 'Forum view: Below node list',
  'ad_pos.forum_view_below_stickies' => 'Forum view: Below stickies',
  'ad_pos.forum_view_below_thread_list' => 'Forum view: Below thread list',
  'ad_pos.member_view_below_tabs' => 'Member view: Below tabs',
  'ad_pos.post_above_content' => 'Post: Above message content',
  'ad_pos.post_below_container' => 'Post: Below message container',
  'ad_pos.post_below_content' => 'Post: Below message content',
  'ad_pos.thread_view_above_messages' => 'Thread view: Above message list',
  'ad_pos.thread_view_below_messages' => 'Thread view: Below message list',
);