<?php
return array (
  'button.attach' => 'Attach files',
  'button.cancel' => 'Cancel',
  'button.confirm' => 'Confirm',
  'button.copy' => 'Copy',
  'button.delete' => 'Delete',
  'button.edit' => 'Edit',
  'button.export' => 'Export',
  'button.hide' => 'Hide',
  'button.import' => 'Import',
  'button.login' => 'Log in',
  'button.merge' => 'Merge',
  'button.move' => 'Move',
  'button.preview' => 'Preview',
  'button.purchase' => 'Purchase',
  'button.save' => 'Save',
  'button.search' => 'Search',
  'button.show' => 'Show',
  'button.sort' => 'Sort',
  'button.submit' => 'Submit',
  'button.translate' => 'Translate',
);