<?php
return array (
  'ad_pos_desc.container_breadcrumb_bottom_above' => 'Inside the page container, directly above the bottom breadcrumb on every page.',
  'ad_pos_desc.container_breadcrumb_bottom_below' => 'Inside the page container, directly below the bottom breadcrumb on every page.',
  'ad_pos_desc.container_breadcrumb_top_above' => 'Inside the page container, directly above the top breadcrumb on every page.',
  'ad_pos_desc.container_breadcrumb_top_below' => 'Inside the page container, directly below the top breadcrumb on every page.',
  'ad_pos_desc.container_content_above' => 'Position inside the page container, directly above the content on every page.',
  'ad_pos_desc.container_content_below' => 'Position inside the page container, directly below the content on every page.',
  'ad_pos_desc.container_header' => 'Position in the header, opposite the logo block.',
  'ad_pos_desc.container_sidebar_above' => 'Appears above the (right) sidebar on every page, if any content is rendered there.',
  'ad_pos_desc.container_sidebar_below' => 'Appears below the (right) sidebar on every page, if any content is rendered there.',
  'ad_pos_desc.container_sidenav_above' => 'Appears above the sidenav (left sidebar) on every page, if any content is rendered there. Note that this column may be hidden on small windows.',
  'ad_pos_desc.container_sidenav_below' => 'Appears below the sidenav (left sidebar) on every page, if any content is rendered there. Note that this column may be hidden on small windows.',
  'ad_pos_desc.forum_overview_bottom' => 'A position that appears at the bottom of the forum overview pages.',
  'ad_pos_desc.forum_overview_top' => 'A position that appears at the top of the forum overview pages.',
  'ad_pos_desc.forum_view_above_node_list' => 'A position that appears just above the node list while viewing a forum. This only appears if there are child nodes to display.',
  'ad_pos_desc.forum_view_above_thread_list' => 'Available above the list of threads while viewing a forum.',
  'ad_pos_desc.forum_view_below_node_list' => 'A position that appears just below the node list while viewing a forum. This only appears if there are child nodes to display.',
  'ad_pos_desc.forum_view_below_stickies' => 'Position visible below the list of sticky threads while viewing a forum. This only appears if there are sticky threads.',
  'ad_pos_desc.forum_view_below_thread_list' => 'Available below the list of threads while viewing a forum.',
  'ad_pos_desc.member_view_below_tabs' => 'Directly below the tabs (and above the tab panes) on every member\'s profile.',
  'ad_pos_desc.post_above_content' => 'This position is above the message content in every post.',
  'ad_pos_desc.post_below_container' => 'This position is below the message container for every post.',
  'ad_pos_desc.post_below_content' => 'This position is below the message content in every post.',
  'ad_pos_desc.thread_view_above_messages' => 'Advertising position above the list of messages when viewing a thread.',
  'ad_pos_desc.thread_view_below_messages' => 'Advertising position below the list of messages when viewing a thread.',
);