<?php
return array (
  'admin_permission.addOn' => 'Gerenciar addons',
  'admin_permission.advertising' => 'Gerenciar anúncios',
  'admin_permission.attachment' => 'Gerenciar arquivos anexados',
  'admin_permission.ban' => 'Manage bans',
  'admin_permission.bbCodeSmilie' => 'Gerenciar BBcodes e emoticons',
  'admin_permission.cron' => 'Manage cron entries',
  'admin_permission.help' => 'Gerenciar ajuda',
  'admin_permission.import' => 'Importar dados',
  'admin_permission.language' => 'Gerenciar idiomas e frases',
  'admin_permission.navigation' => 'Gerenciar navegação',
  'admin_permission.node' => 'Gerenciar nós',
  'admin_permission.notice' => 'Gerenciar avisos',
  'admin_permission.option' => 'Gerenciar opções',
  'admin_permission.payment' => 'Gerenciar provedores de pagamento',
  'admin_permission.reaction' => 'Manage reactions',
  'admin_permission.rebuildCache' => 'Reconstruir caches',
  'admin_permission.style' => 'Manage styles, style properties, and templates',
  'admin_permission.tags' => 'Gerenciar tags',
  'admin_permission.thread' => 'Gerenciar tópicos e posts',
  'admin_permission.trophy' => 'Gerenciar troféus',
  'admin_permission.upgradeXenForo' => 'Upgrade XenForo',
  'admin_permission.user' => 'Gerenciar usuários e moderadores',
  'admin_permission.userField' => 'Gerenciar campos personalizados de usuário',
  'admin_permission.userGroup' => 'Gerenciar grupos de usuários',
  'admin_permission.userUpgrade' => 'Manage user upgrades',
  'admin_permission.viewLogs' => 'Ver registros',
  'admin_permission.viewStatistics' => 'Ver estatísticas',
  'admin_permission.warning' => 'Gerenciar alertas',
  'admin_permission.widget' => 'Gerenciar widgets',
);