<?php
return array (
  'api_scope.attachment_delete' => 'Covers deleting attachments.',
  'api_scope.attachment_read' => 'Covers viewing attachment data.',
  'api_scope.attachment_write' => 'Covers uploading new attachments.',
  'api_scope.auth' => 'Covers testing user name/password authentication. Applies to super-user keys only.',
  'api_scope.conversation_read' => 'Covers viewing conversations.',
  'api_scope.conversation_write' => 'Covers creating or updating conversations.',
  'api_scope.node_delete' => 'Covers deleting a node.',
  'api_scope.node_read' => 'Covers reading the list of nodes or an individual node.',
  'api_scope.node_write' => 'Covers creating or updating a node. Node deletion is not included.',
  'api_scope.profile_post_delete_hard' => 'Covers hard-deleting profile posts and profile post comments.',
  'api_scope.profile_post_read' => 'Covers viewing profile posts and profile post comments.',
  'api_scope.profile_post_write' => 'Covers creating, updating and soft-deleting profile posts and profile post comments.',
  'api_scope.thread_delete_hard' => 'Covers hard-deleting threads and posts.',
  'api_scope.thread_read' => 'Covers reading thread and post information.',
  'api_scope.thread_write' => 'Covers creating, updating and soft-deleting threads and posts.',
  'api_scope.user_delete' => 'Covers deleting a user.',
  'api_scope.user_read' => 'Covers reading user profile information. Note that some profile details may be returned with other data.',
  'api_scope.user_write' => 'Covers updating user profile information.',
);