<?php
return array (
  'button.attach' => 'Anexar arquivos',
  'button.cancel' => 'Cancelar',
  'button.confirm' => 'Confirmar',
  'button.copy' => 'Copiar',
  'button.delete' => 'Excluir',
  'button.edit' => 'Editar',
  'button.export' => 'Exportar',
  'button.hide' => 'Hide',
  'button.import' => 'Importar',
  'button.login' => 'Entrar',
  'button.merge' => 'Mesclar',
  'button.move' => 'Mover',
  'button.preview' => 'Pré-visualizar',
  'button.purchase' => 'Comprar',
  'button.save' => 'Salvar',
  'button.search' => 'Pesquisar',
  'button.show' => 'Show',
  'button.sort' => 'Ordenar',
  'button.submit' => 'Enviar',
  'button.translate' => 'Traduzir',
);