<?php
return array (
  'nav._default' => 'Default (no selected tab)',
  'nav.contributedThreads' => 'Threads with your posts',
  'nav.currentVisitors' => 'Visitantes atuais',
  'nav.defaultLatestActivity' => 'Latest activity',
  'nav.defaultLogOut' => 'Log out',
  'nav.defaultNewsFeed' => 'Your news feed',
  'nav.defaultRegister' => 'Register',
  'nav.defaultYourAccount' => 'Your account',
  'nav.defaultYourProfile' => 'Your profile',
  'nav.findThreads' => 'Buscar tópicos',
  'nav.forumList' => 'Lista de fóruns',
  'nav.forums' => 'Fóruns',
  'nav.home' => 'Página inicial',
  'nav.latestActivity' => 'Última atividade',
  'nav.markForumsRead' => 'Marcar fóruns como lidos',
  'nav.members' => 'Membros',
  'nav.newPosts' => 'Novos posts',
  'nav.newProfilePosts' => 'Novos posts de perfil',
  'nav.registeredMembers' => 'Membros registrados',
  'nav.searchForums' => 'Pesquisar fóruns',
  'nav.searchProfilePosts' => 'Search profile posts',
  'nav.unansweredThreads' => 'Unanswered threads',
  'nav.watched' => 'Watched',
  'nav.watchedForums' => 'Fóruns seguidos',
  'nav.watchedThreads' => 'Tópicos seguidos',
  'nav.whatsNew' => 'Novidades',
  'nav.whatsNewNewsFeed' => 'Seu feed de notícias',
  'nav.whatsNewPosts' => 'Novos posts',
  'nav.whatsNewProfilePosts' => 'Novos posts de perfil',
  'nav.yourThreads' => 'Seus tópicos',
);