<?php
return array (
  'option_group.acp' => 'Painel de controle de administração',
  'option_group.alerts' => 'Alertas de usuário',
  'option_group.appearance' => 'Aparência',
  'option_group.attachments' => 'Anexos',
  'option_group.basicBoard' => 'Informações básicas do fórum',
  'option_group.boardActive' => 'Fórum ativo',
  'option_group.censoringOptions' => 'Censura',
  'option_group.debug' => 'Opções de depuração',
  'option_group.discourager' => 'Desencorajamento e disciplina do usuário',
  'option_group.discussionOptions' => 'Tópicos, discussões e conversas',
  'option_group.emailOptions' => 'Opções de e-mail',
  'option_group.imageLinkProxy' => 'Image and link proxy',
  'option_group.logging' => 'Opções de registro',
  'option_group.mediaEmbedding' => 'Media embedding',
  'option_group.messageOptions' => 'Mensagens',
  'option_group.newsfeed' => 'Feed de notícias',
  'option_group.nodeList' => 'Nó & lista de fórum',
  'option_group.performance' => 'Desempenho',
  'option_group.searchOptions' => 'Opções de pesquisa',
  'option_group.seo' => 'Otimização de mecanismos de busca (SEO)',
  'option_group.serviceProviders' => 'Provedores de serviços externos',
  'option_group.sharing' => 'Compartilhamento',
  'option_group.sitemap' => 'Geração de sitemap XML',
  'option_group.spam' => 'Gerenciamento de spam',
  'option_group.stats' => 'Estatísticas e métricas',
  'option_group.tagging' => 'Marcação de conteúdo',
  'option_group.users' => 'Opções de usuário',
  'option_group.usersAndRegistration' => 'Registro de usuário',
);