<?php
return array (
  'option_explain.acpSearchExclude' => 'When using the quick search facility in the control panel, content from the following types will be searched. Disabling content types here may speed-up searching slightly.',
  'option_explain.addBanUserGroup' => 'Quando um usuário é banido, eles podem ser adicionados a um grupo de usuários específico enquanto o banimento está ativo. Isso permite substituições para seu estilo de grupo de usuários, por exemplo.',
  'option_explain.adminRequireTfa' => 'Se ativado, os administradores não poderão acessar o painel de controle até que tenham ativado a confirmação em duas etapas. Isso não afetará os usuários registrados no painel de controle até o próximo login.',
  'option_explain.adsDisallowedTemplates' => 'You may want to prevent all ads from showing within certain templates, such as errors or other pages that may be against your ad provider\'s ToS. List them above.',
  'option_explain.akismetKey' => '<a href="https://akismet.com/signup/" target="_blank">Akismet</a> é um serviço que verifica comentários e determina se são spam. Se você digitar uma chave Akismet API aqui, as mensagens de usuário serão verificadas para spam. Você pode se inscrever para uma chave de API através de seu site. Se Akismet determinar que uma mensagem é spam, ela terá de ser aprovada manualmente antes de ser exibida.',
  'option_explain.alertExpiryDays' => 'Os alertas de usuário desaparecerão da lista de alertas muitos dias depois de serem visualizados. Os alertas não visualizados expirarão automaticamente após 30 dias.',
  'option_explain.alertsPerPage' => 'Controla quantos alertas são exibidos em cada página da lista de alertas completos dos usuários.',
  'option_explain.alertsPopupExpiryHours' => 'O alerta popup mostrará todos os alertas não vistos, além de quaisquer alertas vistos que foram visualizados dentro do período de tempo (em horas) até agora. Observe que o valor total mostrado neste pop-up é limitado a não mais de 25.',
  'option_explain.allowVideoUploads' => 'Use this option to globally enable or disable video uploads. If enabled, you must give specific users/groups the relevant permissions to upload videos.<br />
<br />
The following additional extensions will be available for upload: {allowedVideoExtensions}.<br />
<br />
You should also provide the maximum video file size in kilobytes (KB). Videos over this size will be rejected. The configuration of this server limits this value to <b>{serverMaxFileSize}</b> KB.',
  'option_explain.allowedCodeLanguages' => 'Os idiomas definidos aqui estarão disponíveis para uso dentro do BBcode código com o formato de [CODE=xxxx].',
  'option_explain.approveSharedBannedRejectedIp' => 'Essa opção permite que o endereço IP de um novo registro seja verificado em relação aos IPs usados recentemente por usuários banidos ou rejeitados. Se uma ou mais correspondências for encontrada, o registro precisará ser aprovado manualmente por um administrador.',
  'option_explain.attachmentExtensions' => 'Liste as extensões de arquivo que podem ser carregadas. Use espaços ou quebras de linha entre extensões.',
  'option_explain.attachmentMaxDimensions' => 'As dimensões máximas permitidas para imagens anexadas (largura x altura). Use 0 ou em branco para não restringir as dimensões.',
  'option_explain.attachmentMaxFileSize' => 'Forneça o tamanho máximo do arquivo anexado em kilobytes (KB). Os anexos acima deste tamanho serão rejeitados. A configuração deste servidor limita esse valor a <b>{serverMaxFileSize}</b> KB.',
  'option_explain.attachmentMaxPerMessage' => 'Use 0 para permitir um número ilimitado de anexos por mensagem. Para desativar anexos de mensagem, use o sistema de permissões.',
  'option_explain.attachmentThumbnailDimensions' => 'A largura e a altura máximas das miniaturas de anexos geradas.',
  'option_explain.autoEmbedMedia' => 'Ative esta opção para que o sistema tente inserir automaticamente mídia de URLs postadas por visitantes que apontam para sites de mídia registrados. Se você optar por incluir um link para o conteúdo, bem, a incorporação de mídia pode ser duplicada quando a mensagem é citada.',
  'option_explain.boardActive' => '',
  'option_explain.boardDescription' => 'Introduza uma descrição para o seu fórum. Isso será colocado dentro da tag de descrição de meta para a página inicial do fórum, então evite usar HTML.',
  'option_explain.boardInactiveMessage' => 'Quando o fórum estiver inativo / fechado, esta mensagem será mostrada aos visitantes do site. Você pode usar HTML.',
  'option_explain.boardTitle' => 'O título do seu fórum. Isso será exibido na parte superior das páginas e usado em e-mails.',
  'option_explain.boardUrl' => 'O URL principal de seu fórum. Não inclua um "/" ou "index.php". O URL deve ser semelhante a este: http://www.exemplo.com.br/forum',
  'option_explain.boardUrlCanonical' => 'Se ativado, a configuração de URL do fórum será tratada como o URL de instalação canônica. Se os visitantes acessarem o seu site através de um URL diferente, eles serão redirecionados para o URL canônico apropriado. Quando ativado, você deve garantir que a configuração do URL do fórum esteja correta. Se não estiver correto, as áreas externas ao painel de controle do administrador não estarão acessíveis!',
  'option_explain.bounceEmailAddress' => 'Se um e-mail não puder ser entregue, a notificação de devolução será devolvida a este endereço de e-mail. Se deixado em branco, as mensagens devolvidas serão devolvidas ao endereço de e-mail padrão. Um valor é necessário aqui se a manipulação automatizada de bounce deve ser ativada. Observe que essa opção pode não funcionar a menos que o parâmetro de caminho de retorno esteja habilitado ou o email seja enviado via SMTP usando a opção Transporte de e-mail.',
  'option_explain.captcha' => 'Os CAPTCHAs ajudam a evitar que os spammers se registrem ou postem.',
  'option_explain.categoryOwnPage' => 'Quando ativado, clicar em um link para uma categoria levará você a uma página dedicada que mostra apenas os filhos dessa categoria. Quando desabilitado, os usuários serão redirecionados para a lista completa do fórum e rolam para a categoria correta.',
  'option_explain.censorCharacter' => 'Esse caractere será repetido para cada caractere em uma palavra censurada que não tenha outra substituição especificada. Por exemplo, se "cão" for censurado, ele pode ser substituído por "***".',
  'option_explain.censorWords' => 'Esta é uma lista de palavras ou frases que devem ser censuradas. Se uma palavra ou frase de substituição for inserida, o texto censurado será reescrito para isso (por exemplo, substituindo "cão" por "gato"). Se nenhuma substituição for inserida, o texto censurado será substituído por caracteres de censura (por exemplo, "***"). <br />
<br />
Se você deseja combinar um caractere curinga no início ou no final da palavra correspondente, adicione um "*" na posição correta. Por exemplo, "cão" não vai censurar "cães", mas "cão*" vontade.',
  'option_explain.changeLogLength' => 'Os dados do registro de alterações de conteúdo serão mantidos por muitos dias. Use 0 para manter os dados de registros de alterações indefinidamente.',
  'option_explain.collectServerStats' => 'XenForo would like to collect some anonymous statistics including your PHP, MySQL and XenForo versions.<br />
<br />
XenForo will not collect any data without your consent, the data will be stored anonymously and we will not collect any user data.',
  'option_explain.contactEmailAddress' => 'Endereço de e-mail onde as mensagens relacionadas ao fórum serão enviadas.',
  'option_explain.contactEmailSenderHeader' => 'Se ativado, os e-mails enviados através do formulário "Contato" serão enviados com a informação do remetente no cabeçalho "De" em vez do cabeçalho "Responder a". Ativar isso pode ajudar em situações em que responder a uma mensagem de contato não vá para o endereço correto, mas pode não ser compatível com todos os servidores SMTP.',
  'option_explain.contactUrl' => 'Esta é a URL da página onde os usuários poderão entrar em contato com você. Observe que a opção de sobreposição só funcionará com URLs XenForo, portanto, se você especificar uma URL externa, provavelmente não funcionará com uma sobreposição.',
  'option_explain.conversationPopupExpiryHours' => 'O popup de conversas mostrará todas as conversas com respostas não lidas, além de todas as conversas lidas cujas respostas mais recentes estejam dentro do intervalo de tempo (em horas) anterior.',
  'option_explain.convertMarkdownToBbCode' => 'If enabled, some Markdown styling will automatically be converted to BB code when saved. Markdown is a simple method for adding formatting by using common patterns such as changing *example* into italics. This can make adding formatting to messages easier, but it can sometimes cause unexpected formatting changes.',
  'option_explain.currentVersionId' => '',
  'option_explain.defaultEmailAddress' => 'Este é o endereço de e-mail padrão do qual os e-mails serão enviados.',
  'option_explain.defaultEmailStyleId' => '',
  'option_explain.defaultLanguageId' => '',
  'option_explain.defaultStyleId' => '',
  'option_explain.disallowedCustomTitles' => 'Digite as palavras ou frases que não são permitidas nos títulos de usuário personalizados. Todas as palavras censuradas são automaticamente desautorizadas. Coloque cada palavra ou frase em linhas separadas.',
  'option_explain.discourageBlankChance' => 'Você pode apresentar aos usuários desencorajados uma página em branco de vez em quando. Digite a porcentagem de chance de isso acontecer.',
  'option_explain.discourageDelay' => 'Usuários desencorajados serão submetidos a um atraso de carregamento de página de um período aleatório entre os dois valores fornecidos aqui.',
  'option_explain.discourageFloodMultiplier' => 'O tempo mínimo padrão entre mensagens pode ser multiplicado para fazer usuários desencorajados esperar mais tempo entre postagem. Digite um multiplicador aqui.',
  'option_explain.discourageRedirectChance' => 'Digite a porcentagem de chance de que um usuário desencorajado seja redirecionado para a página de redirecionamento.',
  'option_explain.discourageRedirectUrl' => 'Você pode redirecionar aleatoriamente os usuários desencorajados para uma página diferente. Deixe em branco para redirecionar para a página inicial do fórum.',
  'option_explain.discourageSearchChance' => 'Quando os usuários desencorajados tentam pesquisar, essa opção define a porcentagem de chance de que ela seja desativada. (0 = nunca, 100 = sempre)',
  'option_explain.discussionPreview' => 'Se habilitado, uma visualização de discussão/tópico aparecerá ao passar o mouse sobre o título.',
  'option_explain.discussionRssContentLength' => 'O número máximo de caracteres de conteúdo a incluir em feeds RSS. Observe que isso inclui qualquer marca BBcode usada na mensagem. 0 desativará o conteúdo de ser incluído em feeds RSS.',
  'option_explain.discussionsPerPage' => 'Isso controla o número máximo de discussões (como tópicos) que serão exibidas em uma página.',
  'option_explain.displayVisitorCount' => 'Quando um usuário logado tem conversas não lidas ou alertas não visualizados, a contagem total pode ser exibida na guia do navegador do usuário antes do título, ou um indicador exibido no favicon ou ambos.',
  'option_explain.dynamicAvatarEnable' => 'Se ativado, um avatar será criado dinamicamente para usuários sem um avatar personalizado. Isso inclui uma letra e uma cor com base em seu nome de usuário. Se desativado, todos os usuários sem um avatar receberão um espaço reservado padrão.',
  'option_explain.editHistory' => 'Se ativado, os moderadores poderão ver as versões históricas das mensagens e comparar as alterações entre elas. Os dados históricos serão apagados após o número especificado de dias. Use 0 para manter o histórico para sempre.',
  'option_explain.editLogDisplay' => 'Se ativado, qualquer edição após o atraso fará com que uma mensagem "última edição" seja exibida no final da mensagem.',
  'option_explain.editorDropdownConfig' => 'This option can\'t be edited manually. It is edited only via the "BB code button manager" page.',
  'option_explain.editorToolbarConfig' => 'This option can\'t be edited manually. It is edited only via the "BB code button manager" page.',
  'option_explain.emailBounceHandler' => 'This option allows the "Bounced email address" account to be automatically read and processed for bounced email reports. This will detect if emails sent to a user bounce, forcing the user to update their email address and preventing the system from emailing them until this happens. This can help reduce the chance of email sent from your board from being considered spam.<br />
<br />
This option will read and remove emails from the specified account when processing. It MUST be directed to an account whose sole purpose is collecting bounce emails from this XenForo installation. A value must be entered for the "Bounced email address" option.',
  'option_explain.emailConversationIncludeMessage' => 'Com esta opção ativada, os e-mails de notificação enviados para destinatários de conversação conterão o texto completo da mensagem sobre a qual eles estão sendo notificados. Com esta opção desativada, eles precisarão visitar o fórum para ler a mensagem.',
  'option_explain.emailFileCheckWarning' => 'Se ativado e nenhum endereço de e-mail for fornecido, os e-mails de <a href="admin.php?options/contactEmailAddress/view">endereço de e-mail de contato</a>.',
  'option_explain.emailSenderName' => 'Se especificado, os e-mails enviados pelo XenForo irão usar como padrão este nome. Se nenhum valor for inserido, o nome do fórum será usado.',
  'option_explain.emailShare' => 'Se um usuário clicar neste botão, o usuário será solicitado a criar um novo e-mail usando seu cliente de e-mail padrão.',
  'option_explain.emailSoftBounceThreshold' => 'If automated bounce processing is enabled, this criteria will be used to determine when multiple soft bounce failures will be considered permanent and emails will no longer be sent to the user.<br />
<br />
All threshold values are limited to bounces generated in the last 30 days.',
  'option_explain.emailTransport' => '',
  'option_explain.emailUnsubscribeHandler' => 'This option allows the "Unsubscribe email address" account to be automatically read and processed for unsubscribe email requests. Requests to this address will disable the "Receive news and update emails" option for users.<br />
<br />
This option will read and remove emails from the specified account when processing. It MUST be directed to an account whose sole purpose is collecting unsubscribe request emails from this XenForo installation. A value must be entered for the "Unsubscribe email address" option.',
  'option_explain.emailWatchedThreadIncludeMessage' => 'Com essa opção ativada, os e-mails de notificação enviados para os usuários seguindo tópicos/fórum conterão o texto completo da mensagem sobre a qual eles estão sendo notificados. Com esta opção desativada, eles precisarão visitar o fórum para ler a mensagem.',
  'option_explain.emojiSource' => 'If you have chosen a value above other than "native" (which will always be served from the device, if available) then you may choose from which source to serve the emoji artwork from.<br />
<br />
By default, we will always serve the graphics from the preferred CDN, though if you wanted to download the artwork and host it yourself, or use a different CDN, you can specify the path here.',
  'option_explain.emojiStyle' => 'Emojis can look vastly different depending on which device you are using. Older devices may not support emoji at all. We can replace native device emoji (or missing emoji) with the artwork sets above.<br />
<br />
<b>Note:</b> Image emojis will only be displayed in areas which support rich text input.',
  'option_explain.enableMemberList' => 'Se ativado, as pessoas poderão procurar uma lista alfabética de usuários. Isso pode ter implicações de desempenho com um grande número de usuários.',
  'option_explain.enableNewsFeed' => 'Com esta opção desabilitada, a visualização do feed de notícias será completamente desativada.',
  'option_explain.enableNotices' => 'Se você não usar o sistema de avisos, você pode desativá-lo completamente e salvar uma consulta na criação da sessão.',
  'option_explain.enablePush' => 'If enabled, a user will be able to subscribe to receive their alerts via devices which are compatible with the Push API. Users will only be able to enable push notifications if they are using a compatible device. This is supported by most major browsers except Safari on macOS and any browser on iOS.<br />
<br />
<strong>Note:</strong> You can only enable this option if you are using PHP 7.1 or above, with the <a href="https://secure.php.net/manual/en/book.gmp.php" target="_blank"><code>gmp</code></a>, <a href="https://secure.php.net/manual/en/book.mbstring.php" target="_blank"><code>mbstring</code></a> and <a href="https://secure.php.net/manual/en/book.openssl.php" target="_blank"><code>openssl</code></a> extensions enabled and have HTTPS enabled.',
  'option_explain.enableSearch' => 'Com esta opção desativada, o mecanismo de pesquisa não funcionará.',
  'option_explain.enableTagging' => 'Tagging is a system that allows keywords to be applied to content to aid searching and content browsing.',
  'option_explain.enableTrophies' => 'Se ativado, seus usuários podem receber <a href="admin.php?trophies/">troféus</a> para concluir determinadas ações ou alcançar determinados marcos. Se desativado, a <a href="admin.php?user-title-ladder/">escada de título do usuário</a> não poderá mais usar Pontos de Troféu.',
  'option_explain.enableVerp' => 'Se ativado, os e-mails enviados incluirão o endereço de e-mail do destinatário no campo de endereço de retorno. Isso permite uma manipulação de e-mails de bounce automatizada mais precisa e mais segura. Se estiver usando o processamento automatizado de bounce, é altamente recomendável ativar esta opção.<br />
<br />
Essa opção requer que a conta de saldo especificada seja uma conta catch-all ou suporte um "+" como um separador de curinga (como no Gmail). Por exemplo, se esta opção estiver ativada com um endereço de bounce de bounce@exemplo.com.br, o e-mail pode ser devolvido para bounce+123abc+user=dominio.com.br@exemplo.com.br.',
  'option_explain.extraCaptchaKeys' => 'This option can\'t be edited manually. It is edited only via the "captcha" option.',
  'option_explain.facebookLike' => 'Se este recurso estiver ativado, um botão Facebook será exibido em várias páginas, incluindo a página de exibição de tópicos, permitindo que usuários do Facebook compartilhem com seus amigos no Facebook.',
  'option_explain.floodCheckLength' => 'Os usuários terão que esperar muitos segundos entre postar mensagens. Os usuários com permissão "Podem ignorar a verificação de flood" serão isentos desta opção.',
  'option_explain.floodCheckLengthDiscussion' => 'Users will have to wait this many seconds between posting new discussions (threads, conversations etc.). If this option is set to 0, the value for \'minimum time between messages\' will be used.',
  'option_explain.fontAwesomeSource' => 'Controla a origem da biblioteca Font Awesome. Você pode hospedar você mesmo (Local) ou usar a fonte CDN recomendada.',
  'option_explain.forumsDefaultPage' => 'Ao entrar na seção de fóruns, esta será a página padrão que os usuários serão levados. Eles poderão acessar a página alternativa através de opções de sub-navegação.',
  'option_explain.geoLocationUrl' => 'The URL specified here will be used to give information (such as a map) about a physical location. The URL must include a <strong>{location}</strong> token.',
  'option_explain.googleAnalyticsAnonymize' => 'If Google Analytics is enabled above and you wish to anonymize IP addresses, you can enable this option.',
  'option_explain.googleAnalyticsWebPropertyId' => 'Você pode inserir sua <a href="http://www.google.com/analytics/">ID do Google Analytics</a> aqui para que o HTML do Google Analytics seja adicionado automaticamente às suas páginas voltadas para o público.',
  'option_explain.gravatarEnable' => 'Se ativado, seus usuários podem obter seus avatares de <a href="http://www.gravatar.com" target="_blank">Gravatar</a>. Quando um novo usuário se registra, o XenForo procurará automaticamente um Gravatar associado ao seu endereço de e-mail. Se desabilitado, isso não removerá Gravatars de usuários que já os tenham.',
  'option_explain.guestShowSignatures' => 'Para maximizar seu sinal para ruído ao exibir tópicos para visitantes, você pode esconder as assinaturas de seus membros.',
  'option_explain.guestTimeZone' => 'Todas as datas e horários serão exibidos para os visitantes neste fuso horário.',
  'option_explain.homePageUrl' => 'Esta é a URL da sua página inicial, fora do fórum. Se esta opção for deixada em branco, \'Página inicial\' não aparecerá na navegação.',
  'option_explain.imageCacheRefresh' => 'If a value greater than 0 is entered, images cached by the image proxy will be refreshed after this many days have passed. This can be used in conjunction with a long cache lifetime to allow images to be updated periodically while retaining resilience against the image being removed. If a value of 0 is entered, images will only be updated when the cache entry expires.',
  'option_explain.imageCacheTTL' => 'Enter the number of days that proxied images should be retained for, before they are removed from your system. If the image is re-requested after this time, it will automatically be fetched again. Use 0 to retain the images indefinitely.',
  'option_explain.imageLibrary' => 'O XenForo pode fazer uso de várias bibliotecas de processamento de imagem diferentes para produzir miniaturas de imagem, etc. Selecione a biblioteca preferida na lista acima.',
  'option_explain.imageLinkProxy' => 'Ao ativar essas opções, você pode proxy e cache imagens e links postados em mensagens através de seu próprio servidor, permitindo rastreamento de cliques etc Proxying de imagens é especialmente importante se você estiver executando o seu site através de SSL (HTTPS).',
  'option_explain.imageLinkProxyKey' => 'Se você tiver ativado a imagem ou o proxy de link, essa chave secreta assegurará que as imagens e os links só serão proxiados se os pedidos tiverem sua origem em seu fórum. Se você achar que os links estão sendo acessados através de sites de terceiros, você pode alterar essa chave secreta para expirar esses links. Todos os links armazenados no fórum serão automaticamente atualizados para usar a nova chave secreta.',
  'option_explain.imageLinkProxyLogLength' => 'This option controls the length of time for which the proxy logs will be maintained after the last request made to an image or a link. If an entry is not requested for this amount of time, its data (including first request time and total accesses) will be removed. Image proxy logs will never be removed unless the image data has been removed (Image cache lifetime). Use 0 to disable pruning of the logs.',
  'option_explain.imageLinkProxyReferrer' => 'If enabled, whenever a proxied image or link is accessed, referrer information will be maintained. This can be viewed in the logs to determine where the image or link has been mentioned. Use 0 to keep the referrer data forever.',
  'option_explain.imageProxyMaxSize' => 'This is the maximum file size for images that are displayed through the image proxy system. An image larger than this will return a placeholder image instead. You may use 0 to disable the limit.',
  'option_explain.includeTitleInUrls' => 'Com essa desativação, um URL como /threads/my-thread.128/ excluiria o título e seria exibido como /threads/128/',
  'option_explain.indexRoute' => 'Se você deseja alterar a página de índice padrão dos fóruns, você pode entrar o caminho de rota aqui. O caminho da rota é a seção do URL para uma página após o URL principal do diretório do fórum, como foruns/ ou paginas/nome-da-pagina/. Não faça referência a um filtro de rota aqui.',
  'option_explain.ipInfoUrl' => 'Specify a URL to be used for requesting more information about an IP address. The URL must include <strong>{ip}</strong>, which will be replaced with the actual IP address.',
  'option_explain.ipLogCleanUp' => 'Old IP logs are rarely useful and simply take up space. They can be pruned after a specified amount of time if desired.',
  'option_explain.jQuerySource' => 'Controla a fonte da biblioteca JavaScript do núcleo do jQuery. Você pode hospedar você mesmo (Local) ou usar uma das fontes CDN recomendadas. Todas as opções de CDN suportam HTTPS / SSL.',
  'option_explain.jsLastUpdate' => 'The Unix time stamp of the last JS update. This can be changed to force a JS recache even if the XF version doesn\'t change.<!-- <span class="js-updateJsLastUpdate">update</span>-->

<script>
/*$(function()
{
	$(\'.js-updateJsLastUpdate\').click(function()
	{
		var d = new Date();
		$(this).closest(\'dd\').find(\'input\').val(d.getTime() / 1000|0);
	});
});*/
</script>',
  'option_explain.lastPageLinks' => 'Se uma discussão abrange várias páginas, as últimas páginas são exibidas na lista de discussão. Defina o número máximo de páginas a mostrar aqui. Defina o número como 0 para desativar esse recurso.',
  'option_explain.lightBoxUniversal' => 'Se esta opção estiver ativada, a sobreposição do Lightbox em que as imagens serão carregadas mostrará todas as imagens anexadas e vinculadas a quente de todas as mensagens na página atual. Se desativado, o Lightbox mostrará apenas imagens da mensagem atual.',
  'option_explain.linkShare' => 'When clicked, the current page link will be copied to the clipboard.',
  'option_explain.loginLimit' => 'Se um usuário falhar ao fazer login 4 ou mais vezes em um período de 15 minutos, esse método será usado para evitar ataques de força bruta.',
  'option_explain.logoLink' => 'Se for fornecido um URL inicial, selecione esta opção para vincular o logotipo da página principal a esse URL. Se esta opção não estiver selecionada, o logótipo sempre irá ligar ao percurso da página de índice.',
  'option_explain.lostPasswordCaptcha' => 'Para evitar que os robôs inundem seu formulário de senha perdida, você pode adicionar proteção CAPTCHA a ele.',
  'option_explain.lostPasswordTimeLimit' => 'Para evitar flood, você pode exigir um atraso entre solicitações de senha perdidas. Insira um período de tempo em segundos que os usuários devem esperar.',
  'option_explain.maxContentSpamMessages' => 'Users will only have their messages checked as spam until they have successfully posted this many messages. Use 0 to disable all spam checks.',
  'option_explain.maxContentTags' => 'This controls the maximum number of tags that can be applied to a piece of content. Use 0 to disable this limit.',
  'option_explain.maxContentTagsPerUser' => 'Beyond controlling the maximum number of tags on a piece of content, you can limit the number of tags each user may apply to prevent a single user from abusing the system. Use 0 to disable this limit.',
  'option_explain.maximumSearchResults' => 'Esse número reflete o número máximo de resultados da pesquisa que serão encontrados, antes que as permissões sejam consideradas. Definir isso muito alto pode causar problemas de desempenho.',
  'option_explain.membersPerPage' => 'Limitar o número de membros para mostrar em cada página da lista de membros registrados e lista de membros online.',
  'option_explain.messageMaxImages' => 'Use 0 para permitir uma quantidade ilimitada de imagens por mensagem.',
  'option_explain.messageMaxLength' => 'O número máximo de caracteres que podem estar em uma mensagem. Isso inclui BBcode. Use 0 para desativar o limite.',
  'option_explain.messageMaxMedia' => 'Use 0 para desativar esse limite. Desativar o limite ou configurá-lo muito alto não é recomendado, já que várias incorporações de mídia podem causar problemas de desempenho do navegador.',
  'option_explain.messagesPerPage' => 'When there are more messages to display than this number, they will be separated into page 2, page 3 etc.',
  'option_explain.moderatorLogLength' => 'The number of days that moderator log records will be kept for. Use 0 to keep the records permanently.',
  'option_explain.multiQuote' => 'A ativação deste sistema permite que várias mensagens em várias páginas sejam selecionadas e citadas em uma única resposta.',
  'option_explain.newsFeedMaxItems' => 'O número máximo de itens de feed de notícias a serem obtidos quando um usuário visualiza seu feed de notícias. Também controla quantos serão armazenados em cache. Os números mais elevados exigem mais recursos, tanto em termos de armazenamento como de tempo de processamento.',
  'option_explain.newsFeedMessageSnippetLength' => 'Quando o texto das mensagens é exibido em itens de notícias, ele será cortado para o comprimento especificado aqui.',
  'option_explain.oEmbedCacheRefresh' => 'If a value greater than 0 is entered, oEmbed data cached by the system will be refreshed after this many days have passed. If a value of 0 is entered, oEmbed data will only be updated when the cache entry expires.',
  'option_explain.oEmbedCacheTTL' => 'Enter the number of days for which fetched oEmbed data should be retained, before they are removed from your system. If the oEmbed data is re-requested after this time, it will automatically be fetched again. Use 0 to retain oEmbed data indefinitely.',
  'option_explain.oEmbedLogLength' => 'Controls how long oEmbed logs are retained after the most recent request for the referenced oEmbed data. Logs are only removed if the oEmbed data has expired and been pruned. Set this to 0 to disable log pruning.',
  'option_explain.oEmbedRequestReferrer' => 'If enabled, whenever oEmbed data is accessed, referrer information will be maintained. This can be viewed in the logs to determine where the embedded media has been mentioned. Use 0 to keep the referrer data forever.',
  'option_explain.onlineStatusTimeout' => 'Depois que um usuário interage com o sistema (clicando em um link etc.) eles serão considerados \'online\'. Eles serão considerados offline se não interagirem com o sistema novamente dentro do tempo especificado aqui.',
  'option_explain.pinterestShare' => 'Este botão permitirá que seus usuários pin seu conteúdo para qualquer pasta Pinterest.',
  'option_explain.plusone' => 'O botão de compartilhamento do Google permite que seus visitantes recomendem páginas de sua instalação do XenForo para outras pessoas.',
  'option_explain.pollMaximumResponses' => 'Isso limitará o número de escolhas que podem ser dadas como respostas a uma enquete.',
  'option_explain.preventDiscouragedRegistration' => 'Você pode impedir que qualquer visitante que navega de <a href="{link}">endereços de IP desencorajados</a> registre novas contas. Eles serão informados de que o registro está atualmente desativado.',
  'option_explain.privacyPolicyForceWhitelist' => 'If you decide to <a href="admin.php?force-agreement/privacy-policy" target="_blank">Force privacy policy agreement</a> then the routes listed here will bypass being redirected to the force agreement page. The route path is the section of the URL to a page after your main forum directory URL, such as forums/ or pages/page-name/. Do not reference a route filter here.',
  'option_explain.privacyPolicyLastUpdate' => 'The Unix time stamp of the last privacy policy update.',
  'option_explain.privacyPolicyUrl' => 'Se inserido, um link de política de privacidade será incluído no rodapé.',
  'option_explain.profilePostMaxLength' => 'O número máximo de caracteres que podem estar em um post de perfil ou comentário. Use 0 para desativar o limite.',
  'option_explain.pushKeysVAPID' => 'This option can\'t be edited manually. It is edited only via the "enablePush" option.',
  'option_explain.readMarkingDataLifetime' => 'Este é o número de dias para manter dados de leitura de marcação (como para tópicos e fóruns). Os dados mais antigos serão sempre vistos como lidos.',
  'option_explain.redditShare' => 'O botão de compartilhamento do <a href="https://www.reddit.com/buttons/" target="_blank">Reddit</a> permite que seus usuários compartilhem seu conteúdo rapidamente e facilmente diretamente para o Reddit.',
  'option_explain.registrationCheckDnsBl' => 'Check IP addresses in DNS block lists when a new user registers to help prevent spam. If the StopForumSpam integration is not enabled, the Tornevall DNSBL will be checked.',
  'option_explain.registrationDefaults' => 'Para manter o formulário de registro curto, muitas preferências não são mostradas. Esta opção permite que você defina os valores padrão para usuários recém-registrados.',
  'option_explain.registrationSetup' => 'Essas opções básicas estabelecem as bases para novos registros no seu fórum.',
  'option_explain.registrationTimer' => 'Use esta opção para definir um número mínimo de segundos que um registro deve realizar antes de ser enviado. Isso pode ajudar a evitar registros de spam. Use 0 para desabilitar esta opção.',
  'option_explain.registrationWelcome' => '',
  'option_explain.reportIntoForumId' => 'Se um fórum for selecionado aqui, o centro de relatório será desativado e um tópico será publicado sempre que o conteúdo for reportado.',
  'option_explain.romanizeUrls' => 'Se selecionado, os caracteres acentuados e não latinos em uma URL serão convertidos para equivalentes latinos, se possível.',
  'option_explain.rootBreadcrumb' => 'Specify the navigation item that will serve as the \'root\' of your breadcrumb list.',
  'option_explain.saveDrafts' => 'Se ativado, os rascunhos serão periodicamente enviados para o servidor e armazenados para permitir que os usuários continuem trabalhando em suas mensagens mais tarde. Desativar isso também desabilitará a verificação automática de novas mensagens ao compor uma resposta.',
  'option_explain.searchMinWordLength' => 'Este é o comprimento mínimo de uma palavra que pode ser pesquisada pelo índice. Com o sistema de pesquisa padrão, isso deve corresponder com o comprimento mínimo de texto mínimo do MySQL (normalmente 4).',
  'option_explain.searchResultsPerPage' => '',
  'option_explain.selectQuotable' => 'Esse recurso permite que os usuários citem trechos de mensagens usando as ferramentas de seleção de texto de seus navegadores.',
  'option_explain.sharedIpsCheckLimit' => 'Ao verificar se outros usuários usaram os mesmos endereços IP, esse controle limita a pesquisa aos últimos X dias.',
  'option_explain.shortcodeToEmoji' => 'If enabled common <code>:short_code:</code> will be converted to emoji and, where supported, we will display suggestions as you type. If an emoji and smilie share the same short code, the smilie will be used.',
  'option_explain.showEmojiInSmilieMenu' => 'If enabled, the smilie menu will display a categorised list of all emoji in addition to your custom smilies.',
  'option_explain.showFirstCookieNotice' => 'Quando um usuário visualiza uma página pela primeira vez (sem cookies XenForo), se ativado, o usuário verá um aviso informando que os cookies são usados por este site e que o uso contínuo consente aos cookies. Esta opção foi concebida para tornar mais fácil o cumprimento das normas de cookies da EU.',
  'option_explain.showMessageOnlineStatus' => 'Se ativado, as mensagens exibirão um ícone se o autor estiver online.',
  'option_explain.sitemapAutoRebuild' => 'Se esta opção estiver ativada, o sitemap será reconstruído automaticamente periodicamente. Se esta opção estiver desativada, o sitemap só será atualizado quando for recriado manualmente por <i>Ferramentas &gt; Reconstruir Caches</i>. O sitemap atual pode ser acessado via <a href="sitemap.php">sitemap.php</a>.',
  'option_explain.sitemapAutoSubmit' => 'Quando um sitemap é criado, se esta opção estiver ativada, a versão atualizada será automaticamente enviada para os mecanismos de pesquisa especificados. {$url} é substituído automaticamente pelo URL do sitemap. Se esta opção não estiver ativada, os mecanismos de pesquisa só saberão sobre o sitemap se ele estiver listado no robots.txt ou se você enviá-lo manualmente para eles.',
  'option_explain.sitemapExclude' => 'Se você deseja excluir certos tipos de conteúdo do sitemap, isso pode ser feito aqui. Observe que o conteúdo deve ser convidado acessível para ser incluído no sitemap, independentemente dessa configuração.',
  'option_explain.sitemapExtraUrls' => 'Se desejar, você pode incluir URLs adicionais que, de outra forma, não seriam incluídos no sitemap. Coloque cada URL em linhas separadas. Observe que esses URLs devem corresponder ao seu URL da placa ou não serão incluídos. Os URLs parciais serão convertidos automaticamente em URLs absolutos.',
  'option_explain.spamDefaultOptions' => 'These are the default options that will be checked when running the spam cleaner. The individual who actually runs the spam cleaner will have the opportunity to alter these options.',
  'option_explain.spamMessageAction' => 'This controls what happens to messages made by spammers when the spam cleaner is applied against them. Note that if content does not support removal from view, it will be permanently deleted regardless of this setting.',
  'option_explain.spamPhrases' => 'Quando qualquer uma dessas frases são inseridas em uma mensagem, a ação abaixo será tomada. Digite uma frase por linha. Você pode usar um * como um curinga para combinar com qualquer palavra. Se você iniciar a linha com /, a linha será tratada como uma expressão regular (exemplo: /teste/i).',
  'option_explain.spamThreadAction' => 'This controls what happens to threads started by spammers when the spam cleaner is applied against them.',
  'option_explain.spamUserCriteria' => 'The spam cleaner will only be available to act against users who meet these criteria. If any of these criteria are set to 0 (zero) they will be ignored.',
  'option_explain.stopForumSpam' => '',
  'option_explain.tagCloud' => 'Se ativada, uma nuvem de tags mostrando as tags mais populares será exibida na página de pesquisa de tags.',
  'option_explain.tagCloudMinUses' => 'Tags will not be shown in the tag cloud unless they have been used at least this many times.',
  'option_explain.tagLength' => 'Isso controla o comprimento mínimo e máximo de tags. Use 0 para desabilitar um limite. As tags nunca podem ter mais de 100 caracteres. Esses limites somente se aplicam quando uma tag é criada. As marcas existentes podem ser sempre utilizadas.',
  'option_explain.tagPosition' => 'Isso controla a posição geral na página onde as tags serão exibidas. A posição exata pode diferir por tipo de conteúdo sendo marcado.',
  'option_explain.tagValidation' => '',
  'option_explain.templateHistoryLength' => 'O número de dias para manter os registros de histórico de edição de modelo. Use 0 para nunca remover o histórico.',
  'option_explain.termsLastUpdate' => 'The Unix time stamp of the last terms and rules update.',
  'option_explain.tosForceWhitelist' => 'If you decide to <a href="admin.php?force-agreement/terms" target="_blank">Force terms and rules agreement</a> then the routes listed here will bypass being redirected to the force agreement page. The route path is the section of the URL to a page after your main forum directory URL, such as forums/ or pages/page-name/. Do not reference a route filter here.',
  'option_explain.tosUrl' => 'Este link será mostrado no rodapé e os usuários terão que concordar com os termos e regras durante o registro.',
  'option_explain.tumblrShare' => 'O <a href="https://www.tumblr.com/docs/en/share_button" target="_blank">botão de compartilhamento do Tumblr</a> permite que seus usuários compartilhem páginas com o Tumblr.',
  'option_explain.tweet' => 'Ativar esse botão permitirá que seus visitantes compartilhem páginas facilmente usando sua conta do Twitter. <br />
<br />
Você também pode especificar até duas contas do Twitter para recomendar aos visitantes depois de usarem o botão Tweet. <a href="https://dev.twitter.com/web/tweet-button/web-intent" target="_blank">Mais informações...</a>',
  'option_explain.unsubscribeEmailAddress' => 'Some email clients support reading a <code>List-Unsubscribe</code> header within emails which enables them to display a prominent option to allow a user to unsubscribe from mailing lists. The mechanism for notifying you about a user\'s request to unsubscribe is an email sent to the address specified here.<br />
<br />
<b>Note:</b> Unless you enable "Automated unsubscribe email handler" below, it will be entirely your responsibility to manually check and process such emails, unless you are using a third party service that will do it for you. A value is required here if you enable the automated option.',
  'option_explain.upgradeCheckStableOnly' => 'When checking for upgrades, by default, we will only look for stable upgrades. Uncheck this box to include "Unsupported" upgrades too.',
  'option_explain.urlToPageTitle' => 'Com isso ativado, se um URL for usado dentro de uma mensagem e não for dado um título pelo autor, sempre que possível o título da página vinculada será buscado e usado em vez disso. <br />
<br />
Use a caixa de texto acima para especificar um formato. <b>{title}</b> será substituído pelo título da página obtida e <b>{url}</b> será substituído pelo URL original. Se nenhum formato for inserido, o título propriamente dito será exibido.',
  'option_explain.urlToRichPreview' => 'If a URL is inserted into a post it can automatically be "unfurled" to display a rich preview of the link contents, such as title, description and image.',
  'option_explain.useFriendlyUrls' => 'Se você habilitar esta opção, os links gerados pelo sistema não incluirão "index.php?". No entanto, para habilitar isso, mod_rewrite deve estar disponível e um arquivo .htaccess apropriado deve estar no lugar.',
  'option_explain.userBanners' => '',
  'option_explain.userMentionKeepAt' => 'O caractere @ é usado para iniciar menções de usuário. Se esta opção estiver desativada, as menções de usuário bem-sucedidas removerão esse caractere.',
  'option_explain.userTitleLadderField' => 'A <a href="admin.php?user-title-ladder/">escada do título do usuário</a> usará este campo para determinar como as pessoas se movimentam na escada.',
  'option_explain.usernameLength' => 'Isso controla o comprimento mínimo e máximo de nomes de usuário. Use 0 para desabilitar um limite. Os nomes de usuário nunca podem ter mais de 50 caracteres.',
  'option_explain.usernameValidation' => '',
  'option_explain.watchAlertActiveOnly' => 'Se ativado, os alertas de conteúdo seguido e os e-mails só serão enviados aos usuários que visitaram dentro do número especificado de dias. Isso pode melhorar o desempenho em instalações grandes ou muito ativas.',
  'option_explain.whatsAppShare' => 'Se um usuário clicar neste botão, o WhatsApp abrirá uma lista de usuários com quem compartilhar o URL e o título da página atual.',
);