<?php
return array (
  'style_prop_group_desc.avatar' => 'Avatars are graphical representations of users. Some users may upload their own images, while others will use the default letter-based imagery. Styling for both of these types is controlled here.',
  'style_prop_group_desc.basic' => '',
  'style_prop_group_desc.bbCode' => 'This section contains properties and options relating to BB codes used to style messages and other user-generated content.',
  'style_prop_group_desc.block' => 'A maior parte do conteúdo dentro do XenForo é apresentada dentro de uma estrutura de \'blocos\', que envolvem conteúdo em uma coleção de caixas HTML, permitindo um estilo muito flexível. As configurações que controlam essas caixas estão localizadas aqui.',
  'style_prop_group_desc.borderSpacing' => 'Settings controlling the thickness and color of structural borders, as well as global settings for element spacing and padding.',
  'style_prop_group_desc.button' => 'Vários tipos de botões de texto estão em uso no XenForo, mas todos compartilham propriedades de estilo comuns, que estão localizadas aqui.',
  'style_prop_group_desc.color' => 'These settings define the colors that will be used throughout the system for specific content or structure types. For consistency and ease of editing, the colors used should come primarily from the Color Palette.',
  'style_prop_group_desc.content' => 'The styling for content areas, namely those areas on which dynamic information is presented, is controlled here.',
  'style_prop_group_desc.dataList' => 'Data lists are used to display content organized into rows and columns (tabular content).',
  'style_prop_group_desc.email' => 'Basic settings for HTML email styling are included here.',
  'style_prop_group_desc.fonts' => 'Settings controlling the style and size of text within the system.',
  'style_prop_group_desc.footer' => 'The lower elements of public-facing pages are controlled here, including the footer background and text styling.',
  'style_prop_group_desc.form' => 'Styling for form structural elements, such as form headers, label columns etc., as well as dimensions for elements within differing viewport sizes, are housed here.',
  'style_prop_group_desc.headerNav' => 'The upper elements of public-facing pages are controlled with these settings, including navigation tabs and the header logo.',
  'style_prop_group_desc.inlineMod' => 'A moderação inline permite que os moderadores tomem ações contra múltiplas partes de conteúdo simultaneamente. Também pode ser exposto a membros através de sistemas como conversas.',
  'style_prop_group_desc.input' => 'Individual form controls - primarily text boxes, are styled here, including focused and disabled variants.',
  'style_prop_group_desc.member' => 'Elements for the special page on which the full information for a user is displayed are styled here.',
  'style_prop_group_desc.menu' => 'Most popup menus within the system share common styling attributes, which are located here.',
  'style_prop_group_desc.message' => 'The various elements that combine to form the main message block, including the message itself, the user info block and the signature, are controlled here.',
  'style_prop_group_desc.misc' => 'Various settings that don\'t fit elsewhere are included here, including badges, chips and animation parameters.',
  'style_prop_group_desc.nodeList' => 'Specific styling elements for the hierarchical list of forums, pages etc. are included here.',
  'style_prop_group_desc.overlay' => 'Common styling controls for the various overlays (windows of content that open over the top of the rest of the page) are found here.',
  'style_prop_group_desc.page' => 'Settings related to the layout of pages and how they respond to different viewport sizes. Also styling for some universal elements.',
  'style_prop_group_desc.palette' => 'This defines the base set of colors that your site will used. Specific usages of these colors can be defined within individual groups.',
  'style_prop_group_desc.rte' => 'The rich text (or WYSIWYG) editor is the preferred method of entering text for messages posted to the forum. Various parts of the editor can be styled with the settings in this group.',
  'style_prop_group_desc.tab' => 'Standalone tabs - those that are not part of the main page navigation, are controlled here.',
  'style_prop_group_desc.tooltip' => 'Tooltips are (usually) small hints that appear when the mouse pointer hovers over page elements that may require additional information to convey their purpose or content.',
);