<?php
return array (
  'widget_def_desc.birthdays' => 'A block containing a heap of avatars of users whose birthday is today.',
  'widget_def_desc.find_member' => 'Adds an auto complete block to the page which allows you to find a member\'s profile by their username.',
  'widget_def_desc.forum_statistics' => 'Exibe um bloco que mostra as estatísticas atuais do fórum sobre coisas como total discussões, mensagem e contagem de membros.',
  'widget_def_desc.html' => 'Widget que permite adicionar HTML personalizado. Este widget suporta a sintaxe do modelo XenForo.',
  'widget_def_desc.member_stat' => 'Displays the list of users from the specified member stat cache.',
  'widget_def_desc.members_online' => 'Exibe um resumo do número de usuários online, visitantes e robôs, além de um resumo dos membros online e das pessoas que você segue.',
  'widget_def_desc.most_messages' => 'Exibe um bloco contendo um amontoado de avatares de usuários que têm a maior quantidade de mensagens.',
  'widget_def_desc.new_posts' => 'Displays a block containing a list of X threads which have most recently been posted in.',
  'widget_def_desc.new_profile_posts' => 'Displays a block containing a list of X recent profile posts.',
  'widget_def_desc.new_threads' => 'Exibe um bloco contendo uma lista de X tópicos que foram criados recentemente.',
  'widget_def_desc.newest_members' => 'A block containing a heap of avatars of users who have recently registered.',
  'widget_def_desc.online_statistics' => 'Displays a block of statistics with a break down of the current visitors on the forum and whether they are registered, guests, or robots.',
  'widget_def_desc.php_callback' => 'Allows you to render the contents of a widget using a PHP callback. The callback should return the \\XF\\Widget\\WidgetRenderer object, set up with the template name and params necessary to render the widget.',
  'widget_def_desc.share_page' => 'Adiciona um conjunto de botões de compartilhamento em um bloco para permitir que a página atual seja compartilhada entre mídias sociais.',
  'widget_def_desc.template_syntax' => 'Widget that creates an associated template which will allow you to display XF template syntax and HTML.',
  'widget_def_desc.thread_poll' => 'Exibe a enquete especificada em um widget.',
  'widget_def_desc.visitor_panel' => 'Displays the visitor\'s avatar and basic information to the visitor about themselves.',
);