<?php
return array (
  'widget_pos.category_view_sidebar' => 'Category view: Sidebar',
  'widget_pos.conversation_list_sidebar' => 'Conversation list: Sidebar',
  'widget_pos.conversation_view_sidebar' => 'Conversation view: Sidebar',
  'widget_pos.find_threads_sidenav' => 'Find threads: Sidenav',
  'widget_pos.forum_list_above_nodes' => 'Forum list: Above nodes',
  'widget_pos.forum_list_below_nodes' => 'Forum list: Below nodes',
  'widget_pos.forum_list_sidebar' => 'Forum list: Sidebar',
  'widget_pos.forum_new_posts_sidebar' => 'Forum new posts: Sidebar',
  'widget_pos.forum_overview_bottom' => 'Forum overview: Bottom',
  'widget_pos.forum_overview_top' => 'Forum overview: Top',
  'widget_pos.forum_view_sidebar' => 'Forum view: Sidebar',
  'widget_pos.help_page_sidenav' => 'Help page: Sidenav',
  'widget_pos.member_view_sidebar' => 'Member view: Sidebar',
  'widget_pos.member_wrapper_sidenav' => 'Member wrapper: Sidenav',
  'widget_pos.online_list_sidebar' => 'Online list: Sidebar',
  'widget_pos.pub_sidebar_bottom' => 'Public: Sidebar bottom',
  'widget_pos.pub_sidebar_top' => 'Public: Sidebar top',
  'widget_pos.thread_view_sidebar' => 'Thread view: Sidebar',
  'widget_pos.whats_new_overview' => 'What\'s new: Overview',
  'widget_pos.whats_new_sidenav' => 'What\'s new: Sidenav',
);