<?php
return array (
  'widget_def.birthdays' => 'Today\'s birthdays',
  'widget_def.find_member' => 'Buscar membro',
  'widget_def.forum_statistics' => 'Estatísticas do fórum',
  'widget_def.html' => 'HTML',
  'widget_def.member_stat' => 'Member stat',
  'widget_def.members_online' => 'Membros online',
  'widget_def.most_messages' => 'Mais mensagens',
  'widget_def.new_posts' => 'New posts',
  'widget_def.new_profile_posts' => 'Novos posts de perfil',
  'widget_def.new_threads' => 'Novos tópicos',
  'widget_def.newest_members' => 'Novos membros',
  'widget_def.online_statistics' => 'Estatísticas online',
  'widget_def.php_callback' => 'PHP callback',
  'widget_def.share_page' => 'Compartilhe esta página',
  'widget_def.template_syntax' => 'Template syntax',
  'widget_def.thread_poll' => 'Tópico de enquete',
  'widget_def.visitor_panel' => 'Visitor panel',
);