<?php
return array (
  'style_prop_group.avatar' => 'Avatars',
  'style_prop_group.basic' => 'Basic options',
  'style_prop_group.bbCode' => 'BB code elements',
  'style_prop_group.block' => 'Blocks',
  'style_prop_group.borderSpacing' => 'Borders and spacing',
  'style_prop_group.button' => 'Buttons',
  'style_prop_group.color' => 'Basic colors',
  'style_prop_group.content' => 'Content areas',
  'style_prop_group.dataList' => 'Data lists',
  'style_prop_group.email' => 'Emails',
  'style_prop_group.fonts' => 'Typography',
  'style_prop_group.footer' => 'Footer',
  'style_prop_group.form' => 'Forms',
  'style_prop_group.headerNav' => 'Header and navigation',
  'style_prop_group.inlineMod' => 'Inline moderation',
  'style_prop_group.input' => 'Inputs',
  'style_prop_group.member' => 'Member profiles',
  'style_prop_group.menu' => 'Popup menus',
  'style_prop_group.message' => 'Messages',
  'style_prop_group.misc' => 'Miscellaneous',
  'style_prop_group.nodeList' => 'Node/forum list',
  'style_prop_group.overlay' => 'Overlays',
  'style_prop_group.page' => 'Page setup',
  'style_prop_group.palette' => 'Color palette',
  'style_prop_group.rte' => 'Rich text editor',
  'style_prop_group.tab' => 'Tabs',
  'style_prop_group.tooltip' => 'Tooltips',
);