<?php
return array (
  'widget_pos_desc.category_view_sidebar' => 'Position in the sidebar of the category_view template. Widget templates rendered in this position can use the current category entity in the <code>{$context.category}</code> param. Widgets here will only be visible if the \'Create pages for categories\' option is enabled.',
  'widget_pos_desc.conversation_list_sidebar' => 'Position in the sidebar while viewing a list of conversations.',
  'widget_pos_desc.conversation_view_sidebar' => 'Position in the conversation_view template sidebar. Widget templates rendered in this position can use the current conversation entity in the <code>{$context.conversation}</code> param.',
  'widget_pos_desc.find_threads_sidenav' => 'Position inside the \'find threads\' side navigation, which is shown only when <i>Appearance &gt; Style properties &gt; Miscellaneous &gt; Find threads navigation style</i> is set to \'Side navigation\'.',
  'widget_pos_desc.forum_list_above_nodes' => 'A position inside the main content area of the forum list above the node tree.',
  'widget_pos_desc.forum_list_below_nodes' => 'A position inside the main content area of the forum list below the node tree.',
  'widget_pos_desc.forum_list_sidebar' => 'Position inside the forum list sidebar for various stats and new content widgets.',
  'widget_pos_desc.forum_new_posts_sidebar' => 'Position inside the forum new posts sidebar for various stats and new content widgets. Note: This page is only available if the default forums page is set to “New posts”.',
  'widget_pos_desc.forum_overview_bottom' => 'A position that appears at the bottom of the forum overview wrapper below the content of the forum list or the new posts list if it is set as the default forum landing page.',
  'widget_pos_desc.forum_overview_top' => 'A position that appears at the top of the forum overview wrapper used by the forum list or the new posts list if it is set as the default forum landing page.',
  'widget_pos_desc.forum_view_sidebar' => 'Position in the sidebar while viewing a list of threads or sub-forums in a forum. Widget templates rendered in this position can use the current forum entity in the <code>{$context.forum}</code> param.',
  'widget_pos_desc.help_page_sidenav' => 'Position inside the Help sidenav, below the navigation block. Widgets here will appear off canvas on narrow displays.',
  'widget_pos_desc.member_view_sidebar' => 'Position in the sidebar while viewing a member\'s profile. Widget templates rendered in this position can use the current user entity in the <code>{$context.user}</code> param.',
  'widget_pos_desc.member_wrapper_sidenav' => 'Displays inside the member wrapper template which wraps the notable members and member lists pages in the sidenav.',
  'widget_pos_desc.online_list_sidebar' => 'Position inside the online_list template sidebar for various online user statistics.',
  'widget_pos_desc.pub_sidebar_bottom' => 'Widget position that appears at the bottom of all public pages. Page specific widgets will always appear above this position.',
  'widget_pos_desc.pub_sidebar_top' => 'Widget position that appears at the top of all public pages. Page specific widgets will always appear below this position.',
  'widget_pos_desc.thread_view_sidebar' => 'Position in the sidebar while viewing a thread. Widget templates rendered in this position can use the current thread entity in the <code>{$context.thread}</code> param.',
  'widget_pos_desc.whats_new_overview' => 'Position inside the whats_new template to display new and recent happenings. This occupies the main column so can support larger widgets.',
  'widget_pos_desc.whats_new_sidenav' => 'Position inside the What\'s new sidenav, below the navigation block. Widgets here will appear off canvas on narrow displays. Only applicable if the side navigation option is selected for the "What\'s new navigation style" style property.',
);